---
title: "Clean Waters Dashboard Data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

## Summary

Create data for the Clean Waters goal page on the OHI Dashboard. This includes the data information table, and individual layer scores.

```{r setup, message = F, warning = F, reslts = 'hide'}

knitr::opts_chunk$set(fig.width = 10, fig.height = 6, fig.path = 'figs/', message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')

library(readr)
library(tidyverse)
library(DT)
```

## Data Wrangling

```{r}

  ## Water quality index. The higher the better
  wqi <- read_csv("~/github/ne-scores/region/layers/cw_wqi.csv") %>%
    mutate(layer = "Water Quality") %>%
    select(rgn_name, rgn_id, year, score, layer)

  ## Sediment quality index. The higher the better
  sqi <- read_csv("~/github/ne-scores/region/layers/cw_sqi.csv") %>%
    mutate(layer = "Sediment Quality") %>%
    select(rgn_name, rgn_id, year, score, layer)

  ## trash calculated from pounds per person. The lower the better so here I inverse the values.
  trash <- read_csv("~/github/ne-scores/region/layers/cw_trash.csv") %>%
    mutate(score = (1-score)*100,
           layer = "Trash") %>%
    left_join(rgn_data) %>%
    select(rgn_name, rgn_id, year, score, layer)

  path <- read_csv("~/github/ne-scores/region/layers/cw_pathogens.csv") %>%
    select(-X1) %>%
    mutate(score = perc_open * 100,
           layer = "Pathogens") %>%
    select(rgn_name, rgn_id, year, score, layer)

  ## combine layers
  cw_data <- wqi %>%
    bind_rows(sqi) %>%
    bind_rows(trash) %>%
    bind_rows(path)

  ## saving cw_data for dashboard -- CONSIDER DOING THIS IN PREP
  write_csv(cw_data, "data/region_layer_scores.csv")
```

## Data Information table

```{r}
cw_data_info <- data.frame(
  Layer = c("Pathogens", "Trash", "Water Quality", "Sediment Quality"),
  Description = c("Number of beach day closures as recorded by the EPA Beach Closure Data",
                  "Pounds of trash collected per person at the Ocean Conservancy’s International coastal cleanup day data",
                  "EPA's National Coastal Condition Assessment Water Quality Index status classifications",
                  "EPA's National Coastal Condition Assessment Sediment Quality Index status classifications"),
  Target = c("100 days free of any beach closures, representing the average length of the swimming season for the region",
             "Zero pounds of trash collected on all beaches on International Coastal Cleanup Day",
             "All monitoring sites classified as in “Good” water quality condition",
             "All monitoring sites classified as in “Good” sediment quality condition"),
  Source = c("[EPA BEACON 2.0](https://watersgeo.epa.gov/beacon2/)",
             "[Ocean Conservancy](https://oceanconservancy.org/trash-free-seas/international-coastal-cleanup/annual-data-release/)",
             "[EPA National Coastal Condition Assessment](https://www.epa.gov/national-aquatic-resource-surveys/ncca)",
             "[EPA National Coastal Condition Assessment](https://www.epa.gov/national-aquatic-resource-surveys/ncca)"
             )
)

write_csv(cw_data_info, "data/cw_data_info.csv")

DT::datatable(cw_data_info)
```






