---
title: "Lasting Special Places Dashboard Data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

```{r setup, message = F, warning = F, reslts = 'hide'}

knitr::opts_chunk$set(fig.width = 10, fig.height = 6, fig.path = 'figs/', message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')

library(readr)
library(tidyverse)
library(DT)
```

## Data Information table

```{r}
lsp_data_info <- data.frame(
  Layer = c("Marine protected areas", "Land protected areas"),
  Description = c("Amount of coastal marine waters with some level of lasting protection that does not include areas managed for fisheries purposes",
                  "Amount of land in the coastal zone (defined as 1km from shore) protected"),
  Target = c("10% of coastal waters protected (Aichi Target 11)", 
             "17% of coastal land (1km from coast) protected ('<a href ="https://www.cbd.int/sp/targets/rationale/target-11/" target = "_blank">Aichi Target 11</a>')"),
  Source = c('<a href="https://maps.usgs.gov/padus/" target = "_blank">USGS Protected Areas Database v2.0</a>',
             '<a href="https://maps.usgs.gov/padus/" target = "_blank">USGS Protected Areas Database v2.0</a>'))


write_csv(lsp_data_info, "data/lsp_data_info.csv")

DT::datatable(lsp_data_info, escape = FALSE)
```






