---
title: "Dashboard Data Viz: Wild Caught Fisheries"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

# Summary
This script creates data used for the OHI Northeast dashboard, specifically for the Wild-Caught Fisheries sub goal. These layers are distinct from the toolbox layers, and are developed specifically for data visualization in the dashboard.

# Setup

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE)
library(tidyverse)

source("~/github/ne-prep/src/R/common.R")
```

# Data wrangling
Create a dataset for the dashboard that shows catch over time by OHI region.

```{r}
catch <- read_csv("data/fish_catch_food_prop_rgn.csv")

assessments <- read_csv("~/github/ne-scores/region/layers/fis_stockscores.csv") 

catch_info <- catch %>%
  left_join(assessments, by = c("species" = "nmfs_original_species", "year", "rgn_id")) %>%
  filter(year > 2002) %>% #show 2003 on since we do calculate rolling averages
  select(year, species, rgn_name, catch, score)

write_csv(catch_info, "data/noaa_catch_dashboard.csv")
```


