---
title: "Nature Serve Data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#install.packages("natserv")
library(natserv)
```

```{r}
options(NatureServeKey = "d314ef4b-033c-4103-be5c-1db9a79b1e35")

ne_spp <- read.csv("data/iucn_spp_in_ne.csv")$sciname
#forloop to grab species uid

full_spp_df <- data.frame(state = NA,
                          status = NA,
                          species = NA,
                          stringsAsFactors = F)

for (i in 1:length(ne_spp)){
  print(i)
  
spp <- ne_spp[i]  

  #first us ns_search to see if the species is in natureserve (tryCatch will skip to next if it's not)
  possibleError <- tryCatch(
      id <- ns_search(x = spp)$globalSpeciesUid,
      error=function(e) e)

if(inherits(possibleError, "error")) next
  
  #then grab the data from natureserve
  possibleError <- tryCatch(
      b  <- ns_data(uid = id),
      error=function(e) e)

if(inherits(possibleError, "error")) next
  
  #get IUCN status
  iucn_stat <- b[[1]]$conservationStatus$other$`IUCN Conservation Status`$statusDescription

  # get the US national rank
  us_rank <- b[[1]]$conservationStatus$natureserve$nationalStatuses$US$rank
  if(is.null(us_rank)) next #if there is no national rank, skip to next species
  
  #create a dataframe to rbind later
  iucn_and_us_df <- data.frame(state = c("IUCN", "USA"), status = c(iucn_stat, us_rank), stringsAsFactors = F) 

  #Now grab state level information
  state <- b[[1]]$conservationStatus$natureserve$nationalStatuses$US$subnationalStatuses

#create an empty dataframe to cycle through each state
out <- data.frame(state = NA,
                  rank = NA)

#forloop goes through each state and finds only those in our region and gets that info. Output is a dataframe
for(j in 1:length(state)){
  
  ST <- state[[j]]$subnationCode

  if(ST %in% c("CT", "NY", "MA", "ME", "RI", "NH")){
    state_rank <- state[[j]]$rank
    
    df <- data.frame(state = ST, rank = state_rank, stringsAsFactors = F)
  }else{
    df <- data.frame(state = NA, rank = NA, stringsAsFactors = F)
  }
  out <- rbind(out, df) %>%
    filter(!is.na(state))
}

spp_df <- out %>%
  mutate(update_rank = 
           ifelse(rank %in% c("SNA", "SNR", "SU", "SNRN"), as.character(us_rank), as.character(rank))) %>%
  select(-rank) %>%
  rename(status = update_rank) %>%
  bind_rows(iucn_and_us_df) %>%
  mutate(species = spp)

full_spp_df <- rbind(spp_df, full_spp_df)

}

write.csv(full_spp_df, file = "data/natureserve_spp_status.csv")
```

