---
title: "Fisheries Dashboard Data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

```{r setup, message = F, warning = F, reslts = 'hide'}

knitr::opts_chunk$set(fig.width = 10, fig.height = 6, fig.path = 'figs/', message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')

library(readr)
library(tidyverse)
library(DT)
```

## Stock assessment data

Combining the RAM and NOAA stock assessment data for display on dashboard

```{r}
ram  <- read_csv("data/ram_stock_assessment_data.csv")
noaa <- read_csv("data/nmfs_stock_assessment_data.csv") %>% select(-X1)

#get same columns as noaa

ram_clean <- ram %>%
  rename(stock = stocklong,
         indicator = metric) %>%
  select(year, stock, indicator, value)

combo <- bind_rows(ram_clean, noaa) %>%
  mutate(indicator = case_when(
    indicator == "b_bmsy" ~ "B/Bmsy",
    indicator == "f_fmsy" ~ "F/Fmsy",
    TRUE ~ as.character(indicator)
  )) %>%
  arrange(stock) %>%
  filter(year > 1999) %>%
  complete(year = 2000:2017,
           indicator,
           stock) %>%
  group_by(indicator) %>%
  fill(value, .direction = "downup")

write_csv(combo, "data/stock_assessment_data_for_dashboard.csv")

```

Calculate % of catch overfished, underfished

```{r}
catch <- read_csv("~/github/ne-scores/region/layers/fis_meancatch.csv")


#fisheries lookup table gives us a list of each species with stock assessment plus info on where they are
lookup_table <- read_csv("data/assessed_species_lookup_table.csv") %>%
  rename(species  = stock_assessment_species_name,
         location = stock_assessment_species_location)

ram_clean <- ram %>% 
  separate(stocklong, into = c("species", "location", "location2", "location3", "location4", "location5"), 
           sep = "(?<=.)(?=[[:upper:]])") %>%
  mutate(source = "RAM",
         location = paste(trimws(location), location2, location3, location4, location5),
         location = trimws(str_replace_all(location, "NA", "")),
         location = str_replace_all(location, "  ", " "),
         species = trimws(species)) %>%
  filter(year>2004) %>%
  select(year, source, species, location, value, metric) 

noaa_clean <- noaa %>% 
  separate(stock, into = c("species", "location"), sep = " - ") %>%
  mutate(source = "NMFS") %>%
  select(year, source, species, location, value, metric = indicator)

combo_clean <- bind_rows(ram_clean, noaa_clean) %>%
  mutate(species = tolower(species)) %>%
  left_join(lookup_table, by = c("source", "species", "location"))

#combine stock assessment data with catch
catch_stock <- catch %>%
  left_join(combo_clean, by = c("species" = "nmfs_original_species", "year", "rgn_id")) %>%
  select(year, rgn_id, species, mean_catch, value, metric, stockid, fixed_name)

#gapfill forward and backward by species and metric

df_gf <- catch_stock %>%
  mutate(metric = case_when(
    metric == "b_bmsy" ~ "B/Bmsy",
    metric == "f_fmsy" ~ "F/Fmsy",
    TRUE ~ as.character(metric)
  )) %>%
  arrange(year) %>%
  group_by(species, stockid, fixed_name) %>%
  mutate(not_assessed = sum(value, na.rm = T)) %>%
  ungroup() %>%
  filter(not_assessed != 0.00) %>%
  select(-not_assessed) %>%
  group_by(species, stockid, fixed_name) 

###TRYING TO GAPFILL STOCKS BACK AND FORWARDS. For example, black seabass should have f/fmsy and b/bmsy gapfilled forwards and backwards before calculating propotion of catch over/under fished.

# %>%
#   complete(metric)
#   mutate(value = zoo::na.locf(value))

```



## Data Information table

```{r}
fis_data_info <- data.frame(
  Layer = c("Catch", "Status"),
  Description = c("Total amount of targeted species caught (pounds) by statistical area",
                  "Stock assessment data on B/Bmsy and F/Fmsy (when available) to indicate health of the stock. This data comes from NMFS for US managed stocks and the RAM Legacy Database for migratory species"),
  Target = c("",
             "B/Bmsy between 0.8 and 1.2, F/Fmsy between 0.66 and 1.2"),
  Source = c('<a href="https://foss.nmfs.noaa.gov/apexfoss/f?p=215:200:5979977158626:::::" target = "_blank">NOAA Fisheries (NMFS) Commercial Landings</a>',
             '<a href="https://www.st.nmfs.noaa.gov/stock-assessment/" target = "_blank">National Marine Fisheries Service (via data request)</a>
             <a href="https://www.ramlegacy.org/" target = "_blank">RAM Legacy Database</a>')
)


write_csv(fis_data_info, "data/fis_data_info.csv")

DT::datatable(fis_data_info, escape = FALSE)
```






