---
title: "code_testing_comp"
author: "Juliette Verstaen"
date: "9/30/2019"
output: html_document
---



https://usgs-r.github.io/ncdfgeom/articles/ncdfgeom.html
```{r}
install.packages("remotes")
remotes::install_github("USGS-R/ncdfgeom")

install.packages("ncdfgeom")

library(sf)
library(tidyverse)
library(ncdfgeom)

# First read the timeseries.
oa_data <- read_timeseries_dsg(file.path(raw_dir,'NOAA_OA/omega_Ar_East_Coast_2014.nc'))
#timeseries id variable was not found in the file. looks like a no go

```


https://r-spatial.github.io/stars/
```{r}
library(stars)

file = file.path(raw_dir,'NOAA_OA/omega_Ar_East_Coast_2014.nc')

oa_file = system.file(file, package = "stars")
(oa = read_ncdf(file, curvilinear = c("lon", "lat"), ignore_bounds = TRUE))

prec_file = system.file("nc/test_stageiv_xyt.nc", package = "stars")
(prec = read_ncdf(prec_file, curvilinear = c("lon", "lat"), ignore_bounds = TRUE))
```

https://cran.r-project.org/web/packages/futureheatwaves/vignettes/starting_from_netcdf.html

```{r}
library(ncdf4)
library(ncdf4.helpers)
library(PCICt)
library(readr)
library(dplyr)
library(tidyr)

filepath = file.path(raw_dir,'NOAA_OA/omega_Ar_East_Coast_2014.nc')
nc_out = nc_open(filepath)

lat <- ncdf4::ncvar_get(nc_out, "lat")
lon <- ncdf4::ncvar_get(nc_out, "lon")

tas_time <- ncdf4.helpers::nc.get.time.series(nc_out, 
                                                      v = OmegaAr,
                                                      time.dim.name = "time")

tas <- ncdf4::ncvar_get(nc_out, v)

ncdf4::nc_close(nc_out)

cat(paste("First and last two dates processed for file named\n",
                  filepath, "are:\n"))
        print(format(tas_time[c(1:2, length(tas_time) - 1:0)],
                     "%Y-%m-%d"))

```




```{r}
library(chron)
library(lattice)
library(RColorBrewer)

tustr <- strsplit(tunits$value, " ")
tdstr <- strsplit(unlist(tustr)[3], "-")
tmonth <- as.integer(unlist(tdstr)[2])
tday <- as.integer(unlist(tdstr)[3])
tyear <- as.integer(unlist(tdstr)[1])
chron(time,origin=c(tmonth, tday, tyear))


```














