---
title: "Mariculture Dashboard Data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

```{r setup, message = F, warning = F, reslts = 'hide'}

knitr::opts_chunk$set(fig.width = 10, fig.height = 6, fig.path = 'figs/', message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')

library(readr)
library(tidyverse)
library(DT)
```

## Data Information table

```{r}
mar_data_info <- data.frame(
  Layer = c("Production", "Sustainability"),
  Description = c("Total amount of farmed species by year and state. This data was put together by hand from individual state and agency reports.",
                  "Seafood Watch sustainability scores based on 10 different criteria. This data is used to weight production."),
  Target = c("Growth in production of 4% annually",
             "NA"),
  Source = c('Put together by hand from available state and agency reports',
             '<a href="https://www.seafoodwatch.org/-/m/sfw/pdf/criteria/aquaculture/mba_seafood%20watch_aquaculture%20standard_version%20a2.pdf?la=en" target = "_blank">Seafood Watch</a>')
)


write_csv(mar_data_info, "data/mar_data_info.csv")

DT::datatable(mar_data_info, escape = FALSE)
```






