---
title: "species_pollution"
author: "Juliette Verstaen"
date: "8/23/2019"
output: html_document
---

``` {r setup,  message = FALSE, warning = FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')  ### an OHINE specific version of common.R
dir_git <- '~/github/ne-prep'
dir_anx <- file.path(dir_M, 'git-annex/neprep')

```



To be filled out!!!

NAS databast

focuses on plants and freshwater
- includes species from other countries and non-native ranges

```{r}
nas <- nas_raw %>% 
    select('Scientific Name', 'Country', 'State', 'County', 'Year', 'Status') %>% 
  mutate(stat = case_when(Status == "established" ~ "established",
                          Status == "eradicated" ~ "eradicated")) %>% 
  rename(sci_name = "Scientific Name") %>% 
  filter(stat != is.na(stat),
         Country %in% 'United States of America',
        # stat %in% 'eradicated',
         State %in% c("ME", "MA", "NY", "RI", "CT", "NH")) %>% 
  filter(Year >= 2005 & Year <= 2017,
         State %in% c("ME", "MA", "NY", "RI", "CT", "NH")) %>%
  select(-Status, -Year) %>% 
  unique() %>% 
  group_by(State) %>% 
  mutate(est_occur = length(which(stat == "established")),
         era_occur = length(which(stat == "eradicated")),
         res = era_occur/est_occur)
```

```{r}
r_gr <- ggplot(nas) +
  geom_bar(aes(x= State, y=res), stat="identity")+
  coord_flip() +
  theme_classic() +
  labs(y = "res", x = "state") +
  ggtitle("NASS ")

r_gr 
```





Maybe delete
```{r}
nas_raw <- read_csv(file.path(dir_anx, "_raw_data/NAS/NAS-Data-Download.csv")) 

nas <- nas_raw %>% 
  select('Scientific Name', 'Country', 'State', 'County', 'Year', 'Status') %>% 
  filter(Country %in% 'United States of America') %>% 
  mutate(database = "nas") %>% 
  rename(sci_name = "Scientific Name") %>% 
  group_by(Year, State) %>% 
  count() %>% 
  ungroup() %>% 
  group_by(State) %>% 
  mutate(hist_min = min(n),
         hist_max = max(n)) %>% 
  ungroup() %>% 
  filter(Year >= 2005 & Year <= 2017) %>% 
  filter(State %in% c("ME", "MA", "NY", "RI", "CT", "NH")) %>% 
  mutate(score = (1-n/hist_max))


nass_graph <- ggplot(nas)+
  geom_line(aes(x=Year, y= score, color= State))

nass_graph

```



Molnar data base
```{r}
library(Hmisc)

d <- mdb.get(file.path(dir_anx, "_raw_data/TNC/TNC_MarineInvasionsDb_18feb08.mdb")) 
nas_raw <- read_csv(file.path(dir_anx, "_raw_data/NAS/NAS-Data-Download.csv")) 

scores <- d[["A_Threat_scores-Marine"]]
species <- d[["_A_SPECIES_MARINE"]]
ecoregions <- d[[30]]
occurances <- d[[3]]
pathways <- d[[4]]


scores_species <- left_join(scores, species, by = c("Species.ID")) %>% 
  select(SPECIES.NAME, Common.name, Ecol.Imp.Score, Scope.Score, Inv.Potl.Score, Mgt.Diff.Score)%>% 
  rename('Scientific Name' = 'SPECIES.NAME') 

invasive <- left_join(nas, scores_species, by = c('Scientific Name')) %>% 
  filter(Year <= 2017 & Year >= 2005,
         State %in% c('ME', 'NH', 'MA', 'RI', 'CT', 'NY'),
         !is.na(Common.name)) %>% 
  unique()



```


