---
title: "Iconic Species Dashboard Data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

```{r setup, message = F, warning = F, reslts = 'hide'}

knitr::opts_chunk$set(fig.width = 10, fig.height = 6, fig.path = 'figs/', message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')

library(readr)
library(tidyverse)
library(DT)
```

## Data Information table

```{r}
ico_data_info <- data.frame(
  Layer = c("Iconic Species List", "Species Location", "Species Status"),
  Description = c("List of species considered iconic in the Northeast",
                  "Species range maps from the Northeast Data Portal and International Union for Conservation of Nature’s (IUCN)",
                  "Species conservation status from NatureServe and IUCN"),
  Target = c("NA", "NA", "No marine species are at risk of extinction and all are classified as of Least Concern using The International Union for Conservation of Nature’s (IUCN) Red List of Threatened Species criteria"),
  Source = c('Sought input from experts in the region to develop this list since there was not a clear widely-accepted source',
             '<a href="https://www.northeastoceandata.org/data-explorer/?mammals-turtles">NE Ocean Data Portal</a>
  <a href="https://www.iucnredlist.org/">IUCN Red List</a>',
             '<a href="https://www.natureserve.org/">NatureServe</a>
             <a href="https://www.iucnredlist.org/">IUCN Red List</a>')
)


write_csv(ico_data_info, "data/ico_data_info.csv")

DT::datatable(ico_data_info, escape = FALSE)
```






