---
title: "Tourism & Recreation dashboard data"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: show
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
    toc: true
---

Creating data layers for use in the data dashboard

```{r setup, include=FALSE, warning = F, message = F}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

library(tidyverse)
```

Filter jobs data from LIV to select just the Tourism & Recreation sector and save in the data folder.

```{r}
tr_jobs <- read_csv("~/github/ne-prep/prep/liv/data/jobs_sector.csv") %>%
  select(-X1) %>%
  filter(Sector == "Tourism & Recreation") %>%
  write.csv("data/tr_jobs.csv")

```



## Data Information table

```{r}
tr_data_info <- data.frame(
  Layer = c("Jobs in Tourism Sectors", "Beach Closures", "Coastal Access"),
  Description = c("National Ocean Economics Program (NOEP) Ocean Economy data for number of jobs in tourism sectors that directly or indirectly depend upon the ocean",
                  "Number of beach day closures as recorded by the EPA Beach Closure Data",
                  "Coastal points identified for human use by NOAA's Environmental Sensitivity Index"),
  Target = c("Annual job growth in ocean related sectors is equal to or greater than the national annual average job growth",
             "At least 100 days free of any beach closures, representing the average length of the swimming season for the region",
             "At least one access point every mile of coastline"),
  Source = c('<a href="http://www.oceaneconomics.org/">National Ocean Economics Program</a>',
             '<a href="https://watersgeo.epa.gov/beacon2/">EPA BEACON 2.0</a>',
             '<a href="https://response.restoration.noaa.gov/maps-and-spatial-data/download-esi-maps-and-gis-data.html">NOAA Office of Response & Restoration</a>')
)

write_csv(tr_data_info, "data/tr_data_info.csv")

DT::datatable(tr_data_info, escape = FALSE)
```
