---
title: "OHIEC: Resilience - Calculating Fishing pressure resilience"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
toc: true
---

``` {r setup,  message = FALSE, warning = FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')  ### an OHINE specific version of common.R

dir_git <- '~/github/ne-prep'
dir_anx <- file.path(dir_M, 'git-annex/neprep')

library(csv)
library(tidyverse)
library(dplyr)
library(Hmisc)
library(stringi)
library(stringr)
library(readxl)
library(tabulizer)
```

some of this code below will probably help 

Apply the same scores to every region
```{r}
enf_com_scores <- enforcement_compliance_scores%>% 
  uncount(11, .id = "n", .remove = F) %>%
  mutate(rgn_name = ifelse(n == 1, "Offshore", 
                       ifelse(n==2, "Georges Bank",
                               ifelse(n==3, "Gulf of Maine",
                                      ifelse(n==4, "Mid-Atlantic Bight",
                                             ifelse(n==5, "Connecticut",
                                                    ifelse(n==6, "Maine",
                                                           ifelse(n==7, "Massachusetts-North",
                                                                  ifelse(n==8, "Massachusetts-South",
                                                                         ifelse(n==9, "New Hampshire",
                                                                                ifelse(n==10, "New York",
                                                                                       "Rhode Island"))))))))))) %>%
  rename(rgn_id=n) %>% 
  mutate(rgn_id = as.character(rgn_id)) %>% 
  select(-enforcement_score_OLE, -enforcement_score_obser)

write.csv(enf_com_scores, file = "data/enf_com_scores.csv")
```

###Calculate Overall Fisheries Resilience Score
```{r}
fish_res_score <- left_join(fisheries_reg_score, ole_scores, by = c("year", "rgn_id", "rgn_name")) %>% 
  rowwise() %>% 
  mutate(score= mean(c(enforcement_score, compliance_score, reg_score), na.rm=T)) %>% 
  select(year, rgn_name, rgn_id, score)

write.csv(fish_res_score, file = "data/fish_res_score.csv")
```

Visualize
```{r}
fisheries_res_graph <- ggplot(fish_res_score)+
  geom_line(aes(x=year, y= score, color= rgn_name))+
 ggtitle("Fisheries Resilience Scores") +
  ylab("Score") +
  xlab("Year") +
  theme_classic()

fisheries_res_graph

##save fig
ggsave("figs/fisheries_res_graph.jpg", width=7, height=5, dpi=300)
```