---
title: "OHIEC: Resilience - Percent species landed that have any sort of management"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
toc: true
---


talk about the data, places where some of the info is found, and how it was manually created


``` {r setup,  message = FALSE, warning = FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')  ### an OHINE specific version of common.R

dir_git <- '~/github/ne-prep'
dir_anx <- file.path(dir_M, 'git-annex/neprep')

library(tidyverse)
library(dplyr)
library(readxl)
```


###4) Percentage of species landed with a management plan or some sort of regulation 

Load in Data
```{r load_data}
species_man_raw <- read_xlsx(file.path(dir_anx, "_raw_data/manually_created/species_management.xlsx"))
```

```{r calculate}
species_man <- species_man_raw %>% 
  group_by(rgn_name, rgn_id) %>% 
  mutate(managed = length(which(managed == "yes")), # need to add locally established here
         total = length(managed),
         species_regulated_score = managed/total) %>% 
  select(rgn_id, rgn_name, species_regulated_score) %>% 
  unique()
```

save this layer
```{r save_layer}
write.csv(species_man, file.path(dir_git, "prep/resilience/ecological/fishing_pressure/data/species_man.csv"))
```










