---
title: "OHIEC: Resilience - Percent species with stock assessment prep"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: false
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ne-prep/src/templates/ohi_hdr.html'
  pdf_document:
toc: true
---

``` {r setup,  message = FALSE, warning = FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      message = FALSE, warning = FALSE)

source('~/github/ne-prep/src/R/common.R')  ### an OHINE specific version of common.R

dir_git <- '~/github/ne-prep'
dir_anx <- file.path(dir_M, 'git-annex/neprep')

library(csv)
library(tidyverse)
library(dplyr)
library(Hmisc)
library(stringi)
library(stringr)
library(readxl)
library(tabulizer)
```


###1) Percentage of Fish Landed with Stock Assessments (target = 100%)

Load Data
```{r load_data}
all_species_caught_assessment_summary <- read_csv("~/github/ne-prep/prep/fis/data/all_species_caught_assessment_summary.csv")
nmfs_spatial_catch_by_ohi_rgn <- read_csv("~/github/ne-prep/prep/fis/data/nmfs_spatial_catch_by_ohi_rgn.csv")
```

Create dataframe of all species ever caught
```{r}
catch <- nmfs_spatial_catch_by_ohi_rgn %>% 
  select(species, rgn_id, rgn_name, year, catch) %>% 
  rename(nmfs_original_species = species) %>% 
  filter(year >= 2005 & year <= 2017)
```

Create dataframe of all species that have ever had a stock assessment done
When mixed or unspecified removed
when peices left it in/renamed so the catch it picked up as assessed species
```{r join_tidy}
assessments <- left_join(catch, all_species_caught_assessment_summary, by = c("nmfs_original_species")) %>% 
  select(year, rgn_id, rgn_name, assessed, nmfs_original_species, catch) %>% 
  mutate(nmfs_original_species = str_replace(nmfs_original_species, "MONK LIVERS",  "MONKFISH / ANGLERFISH / GOOSEFISH"),
         nmfs_original_species = str_replace(nmfs_original_species, "MONK HEADS", "MONKFISH / ANGLERFISH / GOOSEFISH"),
         nmfs_original_species = str_replace(nmfs_original_species, "MONK TAILS", "MONKFISH / ANGLERFISH / GOOSEFISH"),
         nmfs_original_species = str_replace(nmfs_original_species, "SKATE WINGS, LITTLE (SUMMER)",  "SKATE, LITTLE (SUMMER)"),
         nmfs_original_species = str_replace(nmfs_original_species, "SKATE WINGS, WINTER (BIG)", "SKATE, BIG (WINTER)"),
         nmfs_original_species = str_replace(nmfs_original_species, "SKATE WINGS, BARNDOOR", "SKATE, BARNDOOR"), 
         nmfs_original_species = str_replace(nmfs_original_species, "SKATE WINGS, SMOOTH", "SKATE, SMOOTH"),
         nmfs_original_species = str_replace(nmfs_original_species, "SKATE WINGS, THORNY", "SKATE, THORNY"),
         nmfs_original_species = str_replace(nmfs_original_species, "SCALLOPS/SHELLS", "SCALLOP, SEA")) %>% #this one is assessed an bay is not so maybe jsut remove this one
    filter(nmfs_original_species != "CRAB, SPECIES NOT SPECIFIED", 
         nmfs_original_species != "DOGFISH, SPECIES NOT SPECIFIED",
         nmfs_original_species != "EEL, SPECIES NOT SPECIFIED",
         nmfs_original_species != "HAKE, SPECIES NOT SPECIFIED",
         nmfs_original_species != "SEATROUT, SPECIES NOT SPECIFIED",
         nmfs_original_species != "OTHER FOR BAIT",
         nmfs_original_species != "SHRIMP, SPECIES NOT SPECIFIED",
         nmfs_original_species != "SEATROUT, SPECIES NOT SPECIFIED",
         nmfs_original_species != "SHARK, MAKO, SPECIES NOT SPECIFIED",
         nmfs_original_species != "SKATE WINGS",
         nmfs_original_species != "SKATE WINGS, LITTLE/WINTER MIXED",
         nmfs_original_species != "SKATE, LITTLE/WINTER MIXED",
         nmfs_original_species != "TUNA, SPECIES NOT SPECIFIED",
         nmfs_original_species != "AMBERJACK, SPECIES NOT SPECIFIED",
         nmfs_original_species != "CLAM, SPECIES NOT SPECIFIED",
         nmfs_original_species != "CONFIDENTIAL SPECIES",
         nmfs_original_species != "FLOUNDER,NOT SPECIFIED"  ,
         nmfs_original_species != "OTHER INVERTEBRATES",
         nmfs_original_species != "OTHER FINFISH",
         nmfs_original_species != "SHARK, NOT SPECIFIED",
         nmfs_original_species != "SKATE, UNCLASSIFIED",
         nmfs_original_species != "SQUID, SPECIES NOT SPECIFIED",
         nmfs_original_species != "WHELK / CONCH, SPECIES NOT SPECIFIED") %>% 
  mutate(binary_assessed = case_when(
    assessed == "no" ~ 0,
    assessed == "yes" ~ 1)) %>% 
  mutate(weighted_assessed = (catch*binary_assessed))
```

Calculate
```{r calculate}
landed_ass <- assessments %>% 
  group_by(year, rgn_id, rgn_name) %>% 
  mutate(annual_catch = sum(catch),
         annual_catch_ass = sum(weighted_assessed),
         per_catch_landed = annual_catch_ass/annual_catch)%>% 
  select(year, rgn_id, rgn_name, annual_catch, annual_catch_ass,per_catch_landed ) %>% 
  unique()
```

```{r save_data}
write.csv(landed_ass, file = "data/landed_ass.csv")
```

Visualize
```{r visualize}
landed_ass_graph <- ggplot(landed_ass)+
  geom_line(aes(x=year, y= per_catch_landed, color = rgn_name))+
    ggtitle("Percentage of Catch Landed in Northeast with Stock Assessments") +
  ylab("Score") +
  xlab("Year") +
  theme_light()

landed_ass_graph
ggsave("figs/landed_ass_graph.jpg", width=7, height=5, dpi=300)
```


